# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8c43069c0c8f4662a348096e44ea5ca2293032af7afae5b68627963c2c452cba94650d3f09719755fd73401855a008921fbf5700951e403e5013937b86d2b0

test:
  secret_key_base: 75fe3ad019c163b103a08e7d64a21246a76a5b079fa8168566fe6d3d68eee2dabd8a61f3f1153fc34e17a43b59a648e6b1e6b2f7ca7ea6e8bbd9255e2573d3d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
